language: objective-c
osx_image: xcode7.3

git:
  submodules: false

env:
  global:
    - secure: MUWFrjVQKW4xar4ZhYVZmI1N73gRTrg4z9F5kOhxFx6FQDs0eqLDvo5pf2iN05QrSRZlgkUVJZdiXkXigNXCZTWBzINEAle/PwniTxqMi+FehWwkSfLR6v66kaiOpLUjTZmzN4uvziZFNO0BuEvDi8oHsXfy2QOh6x71r8uwv37Dg4qnFw9tquV8bGcuVGc0bD0QeQLMDgXz5iFeXaTAMkAqtJDa3KyR5Lw062UovhFIVQ2ehVYszSoPyr3XqChwSTuIS2vVnlK6J4jct+bp+ynUAcznqjCPxNcF8DfyUJXPnFBfmGhco3RSAHsP2kOhd1uAQBvVZg/Wjd0EGYi4jARNgTVjJUQqJ1iUVOXPtxsih5IcTt2Us4pmmxjlSxtKAxBhrW6zOZm8gxM/gd65Rl1wB3lO3wGINxzZwECjTmyjS9GsngVXinr48EBhLs35vngEfYi4ecGCc2xqhlpDL99v4WPaoUv9dUqInvXH+UNWylxHNat7rjkP2WFGEHm1Z4y80+zHcqA8PLH354YronF4KDch3tndAbOwMHtY8hrw5BE1PhL5etkSYzGeSEgAkLHjI4QfgSo+G6V/y0s9/3rJ/4E/VZcQBSrqyiASEooS2KztqTBa3txYWPvzH7FlJL2qf8pFTn+siNhUDzVY5ya7tniDKB0pfsWqYcFNu+8=

install:
  - carthage bootstrap --use-submodules --no-build

script:
  - set -o pipefail
  - xcodebuild -workspace WooCommerceSDK.xcworkspace -scheme WooCommerceSDK-iOS -sdk iphonesimulator9.2 -destination "OS=9.2,name=iPhone 6s Plus" ONLY_ACTIVE_ARCH=NO | xcpretty -c
  - xcodebuild -workspace WooCommerceSDK.xcworkspace -scheme WooCommerceSDK-tvOS -sdk appletvsimulator9.1 -destination "OS=9.1,name=Apple TV 1080p" ONLY_ACTIVE_ARCH=NO | xcpretty -c
  - xcodebuild -workspace WooCommerceSDK.xcworkspace -scheme WooCommerceSDK-watchOS -sdk watchsimulator2.1 -destination "OS=2.1,name=Apple Watch - 42mm" ONLY_ACTIVE_ARCH=NO | xcpretty -c
  - xcodebuild test -workspace WooCommerceSDK.xcworkspace -scheme WooCommerceSDK-OSX | xcpretty -c
