language: objective-c
osx_image: xcode7.3

git:
  submodules: false

env:
  global:
    - secure: MUWFrjVQKW4xar4ZhYVZmI1N73gRTrg4z9F5kOhxFx6FQDs0eqLDvo5pf2iN05QrSRZlgkUVJZdiXkXigNXCZTWBzINEAle/PwniTxqMi+FehWwkSfLR6v66kaiOpLUjTZmzN4uvziZFNO0BuEvDi8oHsXfy2QOh6x71r8uwv37Dg4qnFw9tquV8bGcuVGc0bD0QeQLMDgXz5iFeXaTAMkAqtJDa3KyR5Lw062UovhFIVQ2ehVYszSoPyr3XqChwSTuIS2vVnlK6J4jct+bp+ynUAcznqjCPxNcF8DfyUJXPnFBfmGhco3RSAHsP2kOhd1uAQBvVZg/Wjd0EGYi4jARNgTVjJUQqJ1iUVOXPtxsih5IcTt2Us4pmmxjlSxtKAxBhrW6zOZm8gxM/gd65Rl1wB3lO3wGINxzZwECjTmyjS9GsngVXinr48EBhLs35vngEfYi4ecGCc2xqhlpDL99v4WPaoUv9dUqInvXH+UNWylxHNat7rjkP2WFGEHm1Z4y80+zHcqA8PLH354YronF4KDch3tndAbOwMHtY8hrw5BE1PhL5etkSYzGeSEgAkLHjI4QfgSo+G6V/y0s9/3rJ/4E/VZcQBSrqyiASEooS2KztqTBa3txYWPvzH7FlJL2qf8pFTn+siNhUDzVY5ya7tniDKB0pfsWqYcFNu+8=

install:
  - carthage bootstrap --use-submodules --no-build

script:
  - set -o pipefail
  - xcodebuild -workspace WooCommerceSDK.xcworkspace -scheme WooCommerceSDK-iOS -sdk iphonesimulator -destination "name=iPhone 6s Plus" ONLY_ACTIVE_ARCH=NO | xcpretty -c
  - xcodebuild -workspace WooCommerceSDK.xcworkspace -scheme WooCommerceSDK-tvOS -sdk appletvsimulator -destination "name=Apple TV 1080p" ONLY_ACTIVE_ARCH=NO | xcpretty -c
  - xcodebuild -workspace WooCommerceSDK.xcworkspace -scheme WooCommerceSDK-watchOS -sdk watchsimulator -destination "name=Apple Watch - 42mm" ONLY_ACTIVE_ARCH=NO | xcpretty -c
  - xcodebuild test -workspace WooCommerceSDK.xcworkspace -scheme WooCommerceSDK-OSX | xcpretty -c

before_deploy:
  - carthage build --no-skip-current
  - carthage archive WooCommerceSDK

deploy:
  provider: releases
  api_key:
    secure: GKoY2RE49AmoG73sc19oeS2/hdDLFlLjHqYPe0ArIb/ovGqMkgSIzGB/iTG2kGtEm20rxTV1EeE8egNuYgtsPl50/wPazACmSvYvRYXizyblH6q1FZV3g4rkzQGI+YM3pgGqYVhF5CsdYyDducYuRFC1BgPnWHonluodvbCZtpIy3wA+I+L69+pxqaNSrj2kaKqXlP6wO6RFJfRgmjkl5ceTNpuVE0TW+NI22EgzSDkfyBfJt1crcB9puiWS2V2KcAVvgOXsLprFNN9J60N6NhzTAhcMq8g/pOUVzkxXIuGDYU4LvOQyRviuRD8AMsaXTACRR+PybTC4NleMDSRE50zrKMSB3Q+Es+2DbGusLOiZ8G2mAGBfjI2qhZ31sFyVnFqI7+QvQ1tByFNswwefyofvdMM9GETlx+fV85DspWDE1Wo4GwOVd8UWh+s4UM6+HZFYBek6Gd31aN/aXsXhqAEWO2QhheC5ycWI/qk6J9O0PMra8HolokcyGjnpDNvOOxcWXEHlaXIvDtfRSl5J34uEyzkYHWS/MNySdoLerDTE7A0Sgsfm0A6MZ6JCR3shyUqc/B9PrbTs6LE2HqhVu3tK7FWPCJqwhUsHo+fJuCmmFpDEYX9twesyl7ozjbvKCnEjfT6y8nfMm25CjLFnyOCRRcaIHSHi0DdZGWeyM9U=
  file: WooCommerceSDK.framework.zip
  skip_cleanup: true
  on:
    tags: true
